// <auto-generated />
using System;
using AspDotNet_MVC.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspDotNet_MVC.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240409051442_dbcontext")]
    partial class dbcontext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.DanhGiaSP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.ToTable("DanhGiaSPs");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.DanhMucSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucSanPham", (string)null);
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.GioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdUser")
                        .IsUnique()
                        .HasFilter("[IdUser] IS NOT NULL");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdGH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSP")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdGH");

                    b.HasIndex("IdSP");

                    b.ToTable("GioHangChiTiet", (string)null);
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<Guid?>("IdDVVC")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHD")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTT")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDVVC");

                    b.HasIndex("IdHD");

                    b.HasIndex("IdSP");

                    b.HasIndex("IdTT");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdDMSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("IdDMSP");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.Shipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shipping", (string)null);
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.ThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.DanhGiaSP", b =>
                {
                    b.HasOne("AspDotNet_MVC.Models.Entitis.SanPham", "SanPham")
                        .WithMany("DanhGiaSPs")
                        .HasForeignKey("SanPhamId");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.GioHang", b =>
                {
                    b.HasOne("AspDotNet_MVC.Models.Entitis.User", "Users")
                        .WithOne("GioHangs")
                        .HasForeignKey("AspDotNet_MVC.Models.Entitis.GioHang", "IdUser");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.GioHangChiTiet", b =>
                {
                    b.HasOne("AspDotNet_MVC.Models.Entitis.GioHang", "GioHangs")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdGH");

                    b.HasOne("AspDotNet_MVC.Models.Entitis.SanPham", "SanPhams")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdSP");

                    b.Navigation("GioHangs");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.HoaDon", b =>
                {
                    b.HasOne("AspDotNet_MVC.Models.Entitis.User", "Users")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdUser");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.HoaDonChiTiet", b =>
                {
                    b.HasOne("AspDotNet_MVC.Models.Entitis.Shipping", "Shippings")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdDVVC");

                    b.HasOne("AspDotNet_MVC.Models.Entitis.HoaDon", "HoaDons")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHD");

                    b.HasOne("AspDotNet_MVC.Models.Entitis.SanPham", "SanPhams")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSP");

                    b.HasOne("AspDotNet_MVC.Models.Entitis.ThanhToan", "ThanhToans")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdTT");

                    b.Navigation("HoaDons");

                    b.Navigation("SanPhams");

                    b.Navigation("Shippings");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.SanPham", b =>
                {
                    b.HasOne("AspDotNet_MVC.Models.Entitis.DanhMucSanPham", "DanhMucSanPhams")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdDMSP");

                    b.Navigation("DanhMucSanPhams");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.DanhMucSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.SanPham", b =>
                {
                    b.Navigation("DanhGiaSPs");

                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.Shipping", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.ThanhToan", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("AspDotNet_MVC.Models.Entitis.User", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
